### ISSUE TITLE
cron options is missing

### ISSUE THREAD

**Issue by dobobaie** [dobobaie/redis-expiry#1]
Is your feature request related to a problem? Please describe.
Acutally `cron` function have only one parameter while `cron-parser` package take 2

Describe the solution you'd like
Add `option` parameter after cron instruction

Technical specifications
Follow [https://www.npmjs.com/package/cron-parser](https://www.npmjs.com/package/cron-parser) package

**Comment by jonathanasquier** [comment]
@dobobaie Add doc in README?
