### ISSUE TITLE
Question on exposed API

### ISSUE THREAD

**Issue by jonathanasquier** [dobobaie/redis-expiry#4]
concerning this:
```
await rexp.update("myKeyByTimeout")("myNewKey");
await rexp.update("myKeyByTimeout", "myValue")("myNewKey");
await rexp.updateByGuuid("Dzokijo")("myNewKey");
```
why not using a similar API as for `set` ?
ex:
```
await rexp.update("myKeyByTimeout").set("myKey", "myValue").timeout(1000);
await rexp.update("myKeyByTimeout", "myValue").set("myKey", "myValue").cron("*/4 * * * * *");
await rexp.updateByGuuid("Dzokijo").set("myKey", "myValue").now()
```
That whould enable the update the value and expiry, not just the key. I often have to update the expiry of a key that is not updated otherwise.

Also aren't keys and guuid a bit redundant?
Also I understand setting listeners on a set of the same keys, but I found the feature less powerful than listening on a regex (and it could prevent having guuid, key, and value by considering key is unique). Do you plan on adding this feature as well?

**Comment by dobobaie** [comment]
It really pertinent what you say about reschedule a key. I think it's a good idea and I will write an issue note about that.  
  
About keys and guuid are very different things. Guuid allows us to create many values for one key. So to do this, we have to make a difference between each same key. Plus, I think guuid is a good way to create an unique key with a reference (key) and a value.  
  
What do you mean by `listening on a regex` ?

**Comment by jonathanasquier** [comment]
@dobobaie I meant
```
rexp.set("mykeyby_timeout", "myvalue1").timeout(4000)
rexp.set("mykeyby_cron", "myvalue2").cron("*/4 * * * * *")

rexp.on(/mykeyby_(.)+/gi, (value, key) => {
  // mykeyby_timeout
  // mykeyby_cron
});

```

**Comment by dobobaie** [comment]
Make sense to me. Scheduled for the next version 👍
